# Title: Derive Co-Occurrence
# Author: Layla Unger
# Last Updated: 2025-05-18
# R version: 4.3.2
# Packages: here, dplyr, stringr, tidytext, tidyr, widyr, wordspace, purrr



##############################################
################ DESCRIPTION #################
##############################################

# This script uses the preprocessed CHILDES corpora to calculate co-occurrence 
# regularities between pairs of words.
# Co-occurrence regularities are measured using t-scores and variants
# of MI in windows of three different sizes: 3, 7, and 11 words

# The include:
# (1) Load preprocessed corpora
# (2) Define a helper function to extract co-occurrence scores
# (2) Define a function that measures word pair co-occurrence frequencies within a specified
#     window size, and converts these frequencies to t-scores/variants of MI following
#     Evert, Stefan (2008). Corpora and collocations. In A. Lüdeling and M. Kytö (eds.), Corpus Linguistics. 
#     An International Handbook, chapter 58, pages 1212-1248. Mouton de Gruyter, Berlin, New York.
# (3) Use function to measure co-occurrence regularities within window sizes of 3, 7, and 11 
#     words.
# (4) Combine regularities in each window size into a single object and save as an .rds file

###############################################
################## PACKAGES ###################
###############################################

library(dplyr)
library(tidyr)
library(widyr)
library(tidytext)
library(stringr)
library(wordspace)
library(purrr)


################################################
############### LOAD CHILDES ###################
################################################

corpora_file <- here("corpus_processing", "data", "CHILDES_corpora_processed.rds")

corpora_text <- readRDS(file = corpora_file)

###############################################
#### FUNCTIONS TO CALCULATE CO-OCCURRENCE #####
###############################################


# Define a helper function that will be used to extract co-occurrence scores
# that are generated by the wordspace package
extract_score <- function(wordspace_matrix, score_name) {
  score_df <- as.data.frame(summary(wordspace_matrix$S))
  score_df$word1 <- rownames(wordspace_matrix$S)[score_df$i]
  score_df$word2 <- colnames(wordspace_matrix$S)[score_df$j]
  colnames(score_df)[colnames(score_df) == "x"] <- score_name
  
  score_df <- score_df[,c(score_name, "word1", "word2")]
  
  return(score_df)
}

# Function that calculates scores for all word pairs that co-occur within
# a given word window
generate_scores <- function(window_size, corpus) {
  
  # This step:
  # Unnests the words into sliding window ngrams to create an object in which each row
  # is a set of words within a sliding window (of size = window_size)
  # Adds a column that indexes the ID of each sliding window (e.g., sliding 
  # window 1, sliding window 2, etc.)
  # Unnests words in sliding window ngrams so that each row is a single word,
  # with the column indexing the ID of the sliding window in which it appeared
  word_windows <- corpus %>%
    tidytext::unnest_tokens(ngram, Text, token = "ngrams", n = window_size) %>%
    dplyr::mutate(ngramID = row_number()) %>%
    tidyr::unite(windowID, ngramID) %>% 
    tidytext::unnest_tokens(word, ngram)
  
  # Counts the number of times each word appears with each other word
  # in the same sliding window ngram
  co_counts <- word_windows %>%
    # count the number of times each word occurs with each other word
    # in the same sliding window ngram (i.e., co-occur)
    # diag=FALSE to not count words co-occurring with themselves
    widyr::pairwise_count(word, windowID, diag = FALSE, sort = TRUE)
  
  
  # Convert the co-occurrence counts into a co-occurrence matrix
  co_matrix <- dsm(target = co_counts$item1, feature = co_counts$item2, score = co_counts$n,
                       raw.freq=TRUE, sort=TRUE)
  
  # Calculate t-scores
  co_matrix_tscore <- dsm.score(co_matrix, score = "t-score",
                                    sparse=TRUE, # Convert negative to 0
                                    normalize=FALSE
  )
  
  # Calculate ppmi
  co_matrix_ppmi <- dsm.score(co_matrix, score = "MI",
                                  sparse=TRUE, # Convert negative to 0
                                  normalize=FALSE
  )
  
  # Extract tscores and ppmi into dataframes with columns indicating the
  # type of score they contain
  tscore_name <- paste("tscore", "_", window_size, sep = "")
  ppmi_name <- paste("ppmi", "_", window_size, sep = "")
  
  tscore <- extract_score(co_matrix_tscore, tscore_name)
  ppmi <- extract_score(co_matrix_ppmi, ppmi_name)
  
  # Combine scores
  scores <- full_join(tscore, ppmi)
  
  scores <- scores %>%
    select(word1, word2, everything())
 
  return(scores)
}


###############################################
########## CALCULATE CO-OCCURRENCE ############
###############################################

# Define window sizes within which to calculate co-occurrence
window_sizes <- c(3, 7, 11)

# Loop over window sizes and bind the results in a list
scores_list <- map(window_sizes, generate_scores, corpus = corpora_text)

# Combine all results with full_join across the list
co_scores <- reduce(scores_list, full_join, by = c("word1", "word2"))

# Set NA values in score columns to 0
co_scores <- co_scores %>%
  mutate(across(matches("_"), ~ replace_na(.x, 0)))

# Save as .rds file
co_file <- here("derive_cooccurrence", "data", "co_scores.rds")
saveRDS(co_scores, file = co_file)
